name: Android - Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  release:
    types:
      - published
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy-android:
    uses: timmo001/workflows/.github/workflows/build-and-deploy-android.yml@master
    secrets:
      ALIAS: ${{ secrets.ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
      SIGN_KEY: ${{ secrets.SIGN_KEY }}
      STORE_KEY_PASSWORD: ${{ secrets.STORE_KEY_PASSWORD }}
    with:
      package-name: dev.timmo.systembridge
